Add a contact form and finish the mobile version
jugosack/Portfolio_Setup_And_Mobile_First pull request #3
Opened 2022-12-06 22:17 UTC by jugosack

Dear Reviewer,

Please find activities towards the general requirements:
-  there are no linter errors](https://github.com/microverseinc/linters-config).
- It is used correct [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).
- Work is documented [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

HTML/CSS requirements
- Followed is yours list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

Project requirements
IMPORTANT NOTE: For each Microverse project, you need to create a separate pull request. [Read how to work with multiple pull requests in your one repository in the most efficient way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/multiple_pull_requests.md).

The section is build for this milestone:
- the contact form in the footer.
- Name field accepts up to 30 chars.
- Email field accepts only emails.
- Message field accepts up to 500 chars.
- All fields have placeholder text.
- All fields have the correct type.
- A user cannot submit the form if one or more of the fields is empty.
- Collect data by using the [Formspree service](https://formspree.io/html).
- In order to lay out the elements on the page you should use Flexbox.

2022-12-06 23:04 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @jugosack , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media2.giphy.com/media/gKIyqq4JESg4p3RW8V/giphy.gif"/> |

## Highlights

- [ ]...✅ Good commit messages
- [ ]...✅ Green linters
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 23:04 UTC, joskalenda commented on index.html
> +    <button type="submit" id="get-intouch">Get In Touch</button>
- [ ] Well done on adding the max-length as required, in addition, kindly add the `required` attribute to all the input fields, this is to activate the validation on submit.

2022-12-06 23:04 UTC, joskalenda commented on style.css
> +  display: flex;
- [x] Kindly make a few touches on the design to correct what is shown in these images, before the `contact me` text, consider using the same margin property as in the image to match this design.
- [x] Your text title is black, am sure you have forgotten to modify it before you submit your work, please fix that too
- [x] Take a look closer at the design, I think it is not centered at all, a big part is laying on the left side, isn't it? please fix that to make it in the center.
- [x] As indicated with the red box in the input forms, please consider making some padding, your placeholders are too much close to the side.
<img width="732" alt="des1" src="https://user-images.githubusercontent.com/77843050/206042899-1bdff69e-98ac-4e74-ac89-8459809fa8f1.png">

2022-12-06 23:04 UTC, joskalenda commented on style.css
> +
- [ ] Following best practices, it is not a good approach to leave commented lines of code, please remove this commented code here to make your code even better and clean

2022-12-07 15:01 UTC, jugosack commented on index.html
> +    <button type="submit" id="get-intouch">Get In Touch</button>
@joskalenda Thank you for your comment. I have fixed the code according to your recommendation.

2022-12-07 15:02 UTC, jugosack commented on style.css
> +  display: flex;
@joskalenda Thank you for your comment. I have fixed the code according to your recommendation.

2022-12-07 15:02 UTC, jugosack commented on style.css
> +
@joskalenda Thank you for your comment. I have fixed the code according to your recommendation.

2022-12-07 15:30 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @jugosack 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️ 
* Professional README file ✔️

## Required Changes:
_Kindly check the comments below_

## Optional:
- [ ] Please consider following best practices when you write commit messages, they should be capitalized sentences in the imperative form such as "Add linters" instead of "adding linters"... 👍 

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 15:30 UTC, ha-manel commented on index.html
> +    <textarea id="msg" name="user_message" placeholder="Write your message here" maxlength="500" required></textarea>
- [ ] Great job with everything, you're almost there 👏 Kindly add padding to the input field as requested by the previous reviewer to match the design in Figma 💯 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/206219662-259fe70e-56dd-402e-aae3-7cf890ef9972.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/206220474-da6b25c2-ee6a-48b6-a726-a807ffe27de9.png)

2022-12-07 16:35 UTC, jugosack commented on index.html
> +    <textarea id="msg" name="user_message" placeholder="Write your message here" maxlength="500" required></textarea>
@ha-manel Thank you for your comment. I have fixed the code adding padding to the input field as requested by the previous reviewer to match the design in Figma according to your recommendation.

<img width="352" alt="Screen Shot 2022-12-07 at 5 34 50 PM" src="https://user-images.githubusercontent.com/4833083/206236881-f875e63d-395c-44b1-9a6b-4a11cfaa6285.png">

2022-12-07 16:44 UTC, ichala approved these changes
Hi @jugosack   ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 17:09 UTC, merged